"""empty message

Revision ID: 04769a2a9449
Revises: b03aff12c70c
Create Date: 2026-05-22 11:07:20.393905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04769a2a9449'
down_revision: Union[str, Sequence[str], None] = 'b03aff12c70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('sender_address', sa.String(), nullable=True))
    op.add_column('deliveries', sa.Column('receiver_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('deliveries', 'receiver_address')
    op.drop_column('deliveries', 'sender_address')
    # ### end Alembic commands ###
