"""empty message

Revision ID: 4d67a74452e9
Revises: 667cbe25a653
Create Date: 2026-05-25 06:33:33.988507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d67a74452e9'
down_revision: Union[str, Sequence[str], None] = '667cbe25a653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deliveries', 'users', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'driver_id')
    # ### end Alembic commands ###
