"""empty message

Revision ID: 667cbe25a653
Revises: 88e46ae47e59
Create Date: 2026-05-22 14:23:46.305126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667cbe25a653'
down_revision: Union[str, Sequence[str], None] = '88e46ae47e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.add_column('deliveries', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deliveries', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'vehicle_id')
    op.drop_column('chat_messages', 'is_resolved')
    # ### end Alembic commands ###
