"""empty message

Revision ID: 88e46ae47e59
Revises: 502e194edfba
Create Date: 2026-05-22 13:13:54.896782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e46ae47e59'
down_revision: Union[str, Sequence[str], None] = '502e194edfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('origin_lat', sa.Float(), nullable=False, server_default='50.4501'))
    op.add_column('deliveries', sa.Column('origin_lng', sa.Float(), nullable=False, server_default='30.5234'))
    op.add_column('deliveries', sa.Column('destination_lat', sa.Float(), nullable=False, server_default='49.8397'))
    op.add_column('deliveries', sa.Column('destination_lng', sa.Float(), nullable=False, server_default='24.0297'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'destination_lng')
    op.drop_column('deliveries', 'destination_lat')
    op.drop_column('deliveries', 'origin_lng')
    op.drop_column('deliveries', 'origin_lat')
    # ### end Alembic commands ###
