"""empty message

Revision ID: fcf7aae3d814
Revises: 4ce824a24c3c
Create Date: 2026-05-20 10:07:32.289647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf7aae3d814'
down_revision: Union[str, Sequence[str], None] = '4ce824a24c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('min_bonuses', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_levels_id'), 'loyalty_levels', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_levels_name'), 'loyalty_levels', ['name'], unique=True)
    op.add_column('users', sa.Column('loyalty_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'loyalty_levels', ['loyalty_level_id'], ['id'])
    op.drop_column('users', 'loyalty_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('loyalty_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'loyalty_level_id')
    op.drop_index(op.f('ix_loyalty_levels_name'), table_name='loyalty_levels')
    op.drop_index(op.f('ix_loyalty_levels_id'), table_name='loyalty_levels')
    op.drop_table('loyalty_levels')
    # ### end Alembic commands ###
